safety/urls.py
from django.urls import path
from . import views

app_name = 'safety'
urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('complaints/view/', views.ViewComplaintView.as_view(),
         name='view_complaints'),
    path('complaints/add/', views.AddComplaintView.as_view(), name='add_complaints'),
    path('complaints/all/', views.ShowPanelComplaints.as_view(),
         name='all_complaints'),
    path('complaints/action/<int:pk>', views.TakeActionAgainstComplaint.as_view(),
         name='take_action_complaints'),
    path('complaints/view/<int:pk>', views.ComplaintDetailView.as_view(),
         name='view_complaint'),
    path('complaints/delete/<int:id>',
         views.withdrawComplaint, name='withdraw_complaint'),
    path('report/add/', views.AddVolunteerAction.as_view(),
         name='add_volunteer_action'),
    path('reports/view/', views.ViewVolunteerReports.as_view(),
         name='volunteer_reports'),
    path('reports/all/', views.AllVolunteerReports.as_view(),
         name='all_volunteer_reports'),
]

womenSafety/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'WomReport Portal Admin'
admin.site.index_title = 'WomReport Admin'
admin.site.site_title = 'WomReport'


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls',
         'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('accounts/login/',
         LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    # App Routes
    path('', include('safety.urls',
         namespace='safety')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/add_action_complaint.html
{% extends 'layout.html' %}
{% load tailwind_filters %}
{% block title %} Update Complaint{% endblock title %}

{% block content %}
<div class="max-w-7xl mx-28">
    <!-- Page Heading -->
    <div class="lg:flex lg:items-center mx-5 my-10 lg:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Update Action on Complaint
            </h2>
            <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
                <div class="mt-2 flex items-center text-sm text-gray-500">
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z"
                            clip-rule="evenodd" />
                        <path
                            d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                    </svg>
                    Under {{ request.user.first_name }} {{ request.user.last_name }}
                </div>
            </div>
        </div>
    </div>
    <form class="w-full max-w-full space-x-14" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                {{ form.action|as_crispy_field }}
            </div>
            <div class="w-full md:w-1/3 px-3">
                {{ form.action_report|as_crispy_field }}
            </div>
        </div>
        <div class="w-full md:w-full px-3">
            {{ form.action_description|as_crispy_field }}
        </div>
        <button
            class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">Update</button>
    </form>
</div>
{% endblock content %}

templates/add_complaint.html
{% extends 'layout.html' %}
{% load tailwind_filters %}
{% block title %} Add Complaint{% endblock title %}

{% block content %}
<div class="max-w-7xl mx-28">
    <!-- Page Heading -->
    <div class="lg:flex lg:items-center mx-5 my-10 lg:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Add Complaint
            </h2>
            <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
                <div class="mt-2 flex items-center text-sm text-gray-500">
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z"
                            clip-rule="evenodd" />
                        <path
                            d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                    </svg>
                    Under {{request.user.first_name}} {{request.user.last_name}}
                </div>
            </div>
        </div>
        <div class="mt-5 flex lg:mt-0 lg:ml-4">
            <a href="{% url 'safety:add_complaints' %}">
                <span class="hidden sm:block">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/pencil -->
                        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path
                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                        Add
                    </button>
                </span>

            </a>
            <span class="hidden sm:block ml-3">
                <a href="{% url 'safety:view_complaints' %}">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/link -->
                        <svg class="-ml-1 mr-2 h-5 w-5 text-white-500" xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                                clip-rule="evenodd" />
                        </svg>
                        View
                    </button>
                </a>
            </span>
            <!-- Page Heading -->
        </div>
    </div>
    <form class="w-full max-w-full space-x-14" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                {{ form.subject|as_crispy_field }}
            </div>
            <div class="w-full md:w-1/3 px-3">
                {{ form.date|as_crispy_field }}
            </div>
        </div>
        <div class="w-full md:w-full px-3">
            {{ form.description|as_crispy_field }}
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                {{ form.proof|as_crispy_field }}
            </div>
        </div>
        <button
            class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">Add</button>
    </form>
</div>
{% endblock content %}

templates/add_volunteer_action.html
{% extends 'layout.html' %}

{% load tailwind_filters %}
{% block title %} Add Volunteer Action{% endblock title %}

{% block content %}
<div class="max-w-7xl mx-28">
    <!-- Page Heading -->
    <div class="lg:flex lg:items-center mx-5 my-10 lg:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Welcome Volunteer
            </h2>
            <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
                <div class="mt-2 flex items-center text-sm text-gray-500">
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z"
                            clip-rule="evenodd" />
                        <path
                            d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                    </svg>
                    Report Here!
                </div>
            </div>
        </div>
        <div class="mt-5 flex lg:mt-0 lg:ml-4">
            <a href="{% url 'safety:add_volunteer_action' %}">
                <span class="hidden sm:block">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/pencil -->
                        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path
                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                        Add
                    </button>
                </span>
            </a>
            <span class="hidden sm:block ml-3">
                <a href="{% url 'safety:volunteer_reports' %}">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/link -->
                        <svg class="-ml-1 mr-2 h-5 w-5 text-white-500" xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                                clip-rule="evenodd" />
                        </svg>
                        View
                    </button>
                </a>
            </span>
            <!-- Page Heading -->
        </div>
    </div>
    <form class="w-full max-w-full space-x-14" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="w-full md:w-1/3 px-3">
                {{ form.date|as_crispy_field }}
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-2">
            <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                {{ form.action|as_crispy_field }}
            </div>
            <div class="w-full md:w-1/3 px-3">
                {{ form.report|as_crispy_field }}
            </div>
        </div>

        <button
            class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
            type="submit">Add Report</button>
    </form>
</div>
{% endblock content %}

templates/list_complaints.html
{% extends 'layout.html' %}
{% block title %} My Complaints{% endblock title %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>


<div class="max-w-7xl mx-28">
    <!-- Page Heading -->
    <div class="lg:flex lg:items-center mx-5 my-10 lg:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                My Complaints
            </h2>
            <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
                <div class="mt-2 flex items-center text-sm text-gray-500">
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z"
                            clip-rule="evenodd" />
                        <path
                            d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                    </svg>
                    Under {{request.user.first_name}} {{request.user.last_name}}
                </div>
            </div>
        </div>
        <div class="mt-5 flex lg:mt-0 lg:ml-4">
            <a href="{% url 'safety:add_complaints' %}">
                <span class="hidden sm:block">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/pencil -->
                        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path
                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                        Add
                    </button>
                </span>
            </a>
            <span class="hidden sm:block ml-3">
                <a href="{% url 'safety:view_complaints' %}">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/link -->
                        <svg class="-ml-1 mr-2 h-5 w-5 text-white-500" xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                                clip-rule="evenodd" />
                        </svg>
                        View
                    </button>
                </a>
            </span>
            <!-- Page Heading -->
        </div>
    </div>

    <!-- Tables -->
    <table class="table text-gray-900 rounded rounded-2xl p-5 border-separate space-y-6 text-sm display" id="table_id">
        <thead class="text-gray-900">
            <tr>
                <th class="p-3">S.No</th>
                <th class="p-3 text-left">Complaint ID</th>
                <th class="p-3 text-left">Title</th>
                <th class="p-3 text-left">Date Added</th>
                <th class="p-3 text-left">Status</th>
                <th class="p-3 text-left">Evidence</th>
                <th class="p-3 text-left">Withdraw</th>
                <th class="p-3 text-left">View Complaint</th>
            </tr>
        </thead>
        <tbody>

            {% for item in complaints %}
            <tr class="p-3 rounded rounded-2xl">
                <td class="p-3 m-2">{{ forloop.counter }}</td>
                <td class="p-3 m-2">{{ item.id }}</td>
                <td class="p-3 m-2">{{ item.subject|truncatechars:14 }}...</td>
                <td class="p-3 m-2">{{ item.date }}</td>
                <td class="p-3 m-2">
                    {% if item.action %}
                    <a href="{{ item.action_report.url }}" class="text-indigo-600 hover:text-indigo-900">
                        {{ item.action }}</a>
                    {% else %}
                    <p>No Action Taken Yet</p>
                    {% endif %}
                </td>
                <td class="p-3 m-2">
                    <a href="{{ item.proof.url }}" class="text-indigo-600 hover:text-indigo-900">
                        Download</a>
                </td>
                <td class="p-3 m-2">
                    <a href="{% url 'safety:withdraw_complaint' item.id %}"
                        class="text-indigo-600 hover:text-indigo-900">
                        Withdraw</a>
                </td>
                <td class="p-3 m-2">
                    <a href="{% url 'safety:view_complaint' item.id %}" class="text-indigo-600 hover:text-indigo-900">
                        View</a>
                </td>
            </tr>
            {% endfor %}
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>
{% endblock content %}

templates/show_panel_complaints.html
{% extends 'layout.html' %}
{% block title %} All Complaints{% endblock title %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>


<div class="max-w-7xl mx-28">
    <!-- Page Heading -->
    <div class="lg:flex lg:items-center mx-5 my-10 lg:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                Welcome Panel
            </h2>
            <div class="mt-1 flex flex-col sm:flex-row sm:flex-wrap sm:mt-0 sm:space-x-6">
                <div class="mt-2 flex items-center text-sm text-gray-500">
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z"
                            clip-rule="evenodd" />
                        <path
                            d="M2 13.692V16a2 2 0 002 2h12a2 2 0 002-2v-2.308A24.974 24.974 0 0110 15c-2.796 0-5.487-.46-8-1.308z" />
                    </svg>
                    Under {{request.user.first_name}} {{request.user.last_name}}
                </div>
            </div>
        </div>
        <div class="mt-5 flex lg:mt-0 lg:ml-4">
            <a href="{% url 'safety:all_complaints' %}">
                <span class="hidden sm:block">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/pencil -->
                        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path
                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                        Complaints
                    </button>
                </span>
            </a>
            <span class="hidden sm:block ml-3">
                <a href="{% url 'safety:all_volunteer_reports' %}">
                    <button type="button"
                        class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <!-- Heroicon name: solid/link -->
                        <svg class="-ml-1 mr-2 h-5 w-5 text-white-500" xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                                clip-rule="evenodd" />
                        </svg>
                        Reports
                    </button>
                </a>
            </span>
            <!-- Page Heading -->
        </div>
    </div>

    <!-- Tables -->
    <table class="table text-gray-900 rounded rounded-2xl p-5 border-separate space-y-6 text-sm display" id="table_id">
        <thead class="text-gray-900">
            <tr>
                <th class="p-3">S.No</th>
                <th class="p-3 text-left">Complaint ID</th>
                <th class="p-3 text-left">Complaintant</th>
                <th class="p-3 text-left">Email</th>
                <th class="p-3 text-left">User Type</th>
                <th class="p-3 text-left">Phone Number</th>
                <th class="p-3 text-left">Subject</th>
                <th class="p-3 text-left">Date Added</th>
                <th class="p-3 text-left">Status</th>
                <th class="p-3 text-left">Evidence</th>
                <th class="p-3 text-left">View Complaint</th>
            </tr>
        </thead>
        <tbody>
            {% for item in complaints %}
            <tr class="p-3 rounded rounded-2xl">
                <td class="p-3 m-2">{{ forloop.counter }}</td>
                <td class="p-3 m-2">{{ item.id }}</td>
                <td class="p-3 m-2">{{ item.complainant.first_name|capfirst }} {{ item.complainant.last_name }}</td>
                <td class="p-3 m-2">{{ item.complainant.email }}</td>
                <td class="p-3 m-2">{{ item.complainant.type }}</td>
                <td class="p-3 m-2">{{ item.complainant.phone_number }}</td>
                <td class="p-3 m-2">{{ item.subject|truncatechars:14 }}...</td>
                <td class="p-3 m-2">{{ item.date }}</td>
                <td class="p-3 m-2">{% if item.action %}
                    <a href="{{ item.action_report.url }}" class="text-indigo-600 hover:text-indigo-900">
                        {{ item.action }}</a>
                    {% else %}
                    <a href="{% url 'safety:take_action_complaints' item.id %}"
                        class="text-indigo-600 hover:text-indigo-900">Update</a>
                    {% endif %}
                </td>
                <td class="p-3 m-2">
                    <a href="{{ item.proof.url }}" class="text-indigo-600 hover:text-indigo-900">
                        Download</a>
                </td>
                <td class="p-3 m-2">
                    <a href="{% url 'safety:view_complaint' item.id %}" class="text-indigo-600 hover:text-indigo-900">
                        View</a>
                </td>
            </tr>
            {% endfor %}
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#table_id').DataTable();
    });
</script>
{% endblock content %}